apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-session
spec:
  selector:
    matchLabels:
      app: game-session
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: game-session
        tier: backend
    spec:
      containers:
      - name: game-session
        image: game_session:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        envFrom:
         - configMapRef:
             name: env-config
        ports:
        - name: game-session
          containerPort: 443
        volumeMounts:
        - name: certs
          mountPath: "/certs"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: tls-certificate
