apiVersion: v1
kind: Service
metadata:
  name: game-session
  labels:
    app: game-session
    tier: backend
spec:
  ports:
  - port: 443
    targetPort: game-session
  selector:
    app: game-session
    tier: backend
