
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kooky-ingress
  annotations:
    nginx.org/grpc-services: "grpc-svc"
    nginx.org/websocket-services: "ws-svc"
    nginx.org/ssl-services: "ssl-svc"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: “true”
spec:
  tls:
  - hosts:
    - kooky.app
    secretName: env-secret
  rules:
  - host: kooky.app
    http:
      paths:
      - path: /api/v1/session
        backend:
          serviceName: game-session
          servicePort: 443
      - path: /ws
        backend:
          serviceName: game-session
          servicePort: 8008
      - path: /wss
        backend:
          serviceName: game-session
          servicePort: 8008
      - path: /game_session.GameSessionService
        backend:
          serviceName: game-session
          servicePort: 50051
